twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : cmd_vel
        timeout : 0.5
        priority: 50
      keyboard:
        topic   : cmd_vel_key
        timeout : 0.5
        priority: 100
      avoidance:
        topic   : cmd_vel_avoidance
        timeout : 0.5
        priority: 200
      gamepad:
        topic   : cmd_vel_gamepad
        timeout : 0.5
        priority: 100
      block_all:
        topic   : cmd_vel_block_all
        timeout : 0.5
        priority: 255
      block_nav:
        topic   : cmd_vel_block_navigation
        timeout : 0.5
        priority: 75



             
   

